### ISSUE TITLE
Should fail when the feature file cannot be loaded

### ISSUE THREAD

**Issue by dcendents** [bmsantos/cola-tests#51]
Hi,

I'm starting a new project at work which requires ant to build. So I'm using instrumentation to run the JUnit tests, both in ant and in eclipse, which works fine.

However I was surprised to see that the following test did pass given that I don't have the feature file in the project. I wanted to see it fail to make sure the instrumentation was working correctly.

```java
@Features("blabla")
public class BlablaTest extends AbstractBaseColaTest {

	@Test
	public void something() {

	}

    @Given("a <beverage>")
    public void chooseBeverage(@Projection("beverage") final String beverage) {
    }

    @When("a google search is performed")
    public void performGoogleSearch() {
    }

    @Then("the <beverage> wikipedia entry will be present")
    public void verifyBeverageIsPresentInWikipedia(@Projection("beverage") final String beverage) {
        fail("Failed!");
    }
}
```

In a strict BDD test class, I suppose there would not be @Test annotations, so it would fail with a message: java.lang.Exception: No runnable methods

But given a test class with a Features annotation, I think the tests should fail if any of the feature file(s) listed cannot be loaded.

On a side-note, this is the first time I'll use it at work, it's a small project where I am the only developer so the context is perfect. I'll do a presentation later this year on BDD to my colleagues and I hope I'll convince more people to use it. 

Thanks

**Comment by bmsantos** [comment]
Daniel,

Thanks for pointing that out. Yes, you are correct. The test is should fail and the specific error reported back. It seems that there is some exception mishandling.
I'll have a look later today.

Thanks
